org.gradle.jvmargs=-Xmx3G -Dfile.encoding=UTF-8 -Dorg.gradle.internal.vfs.watch=false
org.gradle.daemon=false

## Environment Properties
minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.4.10
forge_version_range=[47,)
loader_version_range=[47,)
mapping_channel=official
mapping_version=1.20.1

## Mod Properties
mod_id=nofeetplace
mod_name=禁止脚下放方块 (No Feet Place)
mod_license=All Rights Reserved
mod_version=1.2.0
mod_group_id=com.chaosz.nofeetplace
mod_authors=ChaosCraft
mod_description=禁止玩家腾空时放置方块，防止垫脚垫高。水里、梯子上、载具里、岩浆里不拦。Prevents players from placing blocks while airborne.
